//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Virsagi.Web.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virsagi is a Singapore registered company that has been involved in the training and test of workers since 1998. Virsagi has several training centers in Dhaka and operates several BCA test centers..
        /// </summary>
        public static string AboutUsContent1 {
            get {
                return ResourceManager.GetString("AboutUsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virsagi has mobilized Bangladeshi workers for the market since 1998 and works with many Dhaka and Singapore Recruitment Agents. We are wholesale suppliers of Bangladeshi workers..
        /// </summary>
        public static string AboutUsContent2 {
            get {
                return ResourceManager.GetString("AboutUsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no cost involved. We have the largest pool of Dhaka Agents and complement the sourcing efforts of Singapore Employers/Employment Agencies. We also complement the marketing efforts of Dhaka Agents, once you register with us, you have access to a very large pool of Singapore Employers/Employment Agents..
        /// </summary>
        public static string BottomContent {
            get {
                return ResourceManager.GetString("BottomContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers of Bangladeshi workers, Singapore LIcensed Employment Agents are welcome to browse this website. If you have an interest in employing workers from Bangladesh, please feel free to contact any of the Employment Agents listed below..
        /// </summary>
        public static string ContactUsContent {
            get {
                return ResourceManager.GetString("ContactUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the Program Works.
        /// </summary>
        public static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Workers.
        /// </summary>
        public static string RegisterWorkers {
            get {
                return ResourceManager.GetString("RegisterWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Dhaka Licensed Employment Agents can register their workers on this website for the purpose of seeking jobs in Singapore. Once your workers are registered, there is no further need for you to market their bios, since the website will do this work for you. To register your workers, simply fill in the form below and click submit button..
        /// </summary>
        public static string RegisterWorkersContent {
            get {
                return ResourceManager.GetString("RegisterWorkersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Workers.
        /// </summary>
        public static string RequestWorkers {
            get {
                return ResourceManager.GetString("RequestWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the online form to request for workers. A representative of an Employment Agency will be in touch within one(1) day to confirm your request..
        /// </summary>
        public static string RequestWorkersContent {
            get {
                return ResourceManager.GetString("RequestWorkersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers intending to work in Singapore must register their bios with any Dhaka Licensed Recruitment Agent..
        /// </summary>
        public static string Step1Content {
            get {
                return ResourceManager.GetString("Step1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhaka Licensed Recruitment Agent will then register their workers on this website..
        /// </summary>
        public static string Step2Content {
            get {
                return ResourceManager.GetString("Step2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website agents market the workers to Licensed Singapore Recruitment Agents/Employers..
        /// </summary>
        public static string Step3Content {
            get {
                return ResourceManager.GetString("Step3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When IPAs are approved, website agents will coordinate with Dhaka Agent/S’pore Agent or Employer to bring workers to Singapore..
        /// </summary>
        public static string Step4Content {
            get {
                return ResourceManager.GetString("Step4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why you should use Virsagi website.
        /// </summary>
        public static string Why {
            get {
                return ResourceManager.GetString("Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most time consuming work for a Singapore Agent/Employer is to source for reliable Dhaka agents who have workers bios for placements. The most time consuming work for a Dhaka Agent is to source for reliable Singapore agents/Employers. Our own contacts are usually limited. By using the Virsagi website, the job is done for you. Thus, Singapore Agents need only to spend time on procuring orders from Employers, and Dhaka Agents need only to spend time on sourcing for more qualified workers. Using the Virsagi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhyContent {
            get {
                return ResourceManager.GetString("WhyContent", resourceCulture);
            }
        }
    }
}
