//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int AgentID { get; set; }
        public string RLName { get; set; }
        public string RLNo { get; set; }
        public string RLAddress { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
