//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitCounter
    {
        public int HitCounterID { get; set; }
        public int TotalCount { get; set; }
        public int MonthlyCount { get; set; }
    }
}
