//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPA
    {
        public int IPAID { get; set; }
        public string PassportNo { get; set; }
        public string WorkerName { get; set; }
        public string Employer { get; set; }
        public string WorkPermitNo { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime IssuanceDate { get; set; }
    }
}
