//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsHeadline1 { get; set; }
        public string NewsDetails1 { get; set; }
        public string NewsHeadline2 { get; set; }
        public string NewsDetails2 { get; set; }
        public string NewsHeadline3 { get; set; }
        public string NewsDetails3 { get; set; }
        public System.DateTime LastUpdatedBy { get; set; }
    }
}
