//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virsagi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerRequest
    {
        public int WorkerRequestID { get; set; }
        public int RequestType { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string CompanyUENNumber { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Details { get; set; }
        public string SpecialRequest { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
